name: UR Monitor

on:
  schedule:
    - cron: "*/30 * * * *"   # 30分ごと（UTC）。スクリプト側でJST時間帯を判定
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # .state.json をコミットするため
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run monitor
        env:
          CHATWORK_TOKEN: ${{ secrets.CHATWORK_TOKEN }}
          CHATWORK_ROOM_ID: ${{ secrets.CHATWORK_ROOM_ID }}
        run: python ur_monitor.py   # ur_monitor.py がリポ直下にある前提

      - name: Persist state
        if: always()
        run: |
          git config user.name "ur-monitor-bot"
          git config user.email "bot@example.com"
          git add .state.json || true
          git commit -m "state update" || true
          git push || true
