name: watchdog
on:
  schedule:
    - cron: "*/5 * * * *"          # 5分おき（UTC）
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read

jobs:
  ensure-ur-monitor:
    runs-on: ubuntu-24.04
    steps:
      - name: 現在がJST 09:30–19:00か判定
        id: gate
        run: |
          jst_hm=$(TZ=Asia/Tokyo date +%H%M)
          if (( 10#$jst_hm < 930 || 10#$jst_hm >= 1900 )); then
            echo "outside=true" >> $GITHUB_OUTPUT
          fi

      - name: 直近の実行時刻を取得（UR Monitor）
        if: steps.gate.outputs.outside != 'true'
        id: last
        env:
          GH_TOKEN: ${{ secrets.PAT_WORKFLOW }}
        run: |
          set -e
          repo="${GITHUB_REPOSITORY}"
          wf_path=".github/workflows/ur-monitor.yml"   # ←実ファイルパス
          # workflow ID を取得（ファイル名解決の曖昧さを排除）
          wf_id=$(gh api /repos/$repo/actions/workflows --jq \
                 ".workflows[] | select(.path==\"$wf_path\").id" || true)

          if [ -z "$wf_id" ]; then
            echo "⚠️ workflow id not found for $wf_path。stale とみなす"
            echo "stale=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # 最新 run の作成時刻を取得
          last_created_at=$(gh api /repos/$repo/actions/workflows/$wf_id/runs \
            -f per_page=1 --jq '.workflow_runs[0].created_at' || true)

          echo "last_created_at=${last_created_at:-<none>}"

          # 値が無い / 404 など異常応答 / パース不能 はすべて “stale”
          if [ -z "$last_created_at" ] || [ "$last_created_at" = "null" ] \
             || ! date -u -d "$last_created_at" >/dev/null 2>&1; then
            echo "stale=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          last_ts=$(date -u -d "$last_created_at" +%s)
          now_ts=$(date -u +%s)
          # 12分以上空いていたら “穴”
          if [ $last_ts -lt $(( now_ts - 12*60 )) ]; then
            echo "stale=true" >> $GITHUB_OUTPUT
          fi

      - name: バックアップ発火（workflow_dispatch）
        if: steps.gate.outputs.outside != 'true' && steps.last.outputs.stale == 'true'
        env:
          GH_TOKEN: ${{ secrets.PAT_WORKFLOW }}
        run: |
          branch="${GITHUB_REF_NAME:-main}"
          echo "dispatch ur-monitor on $branch"
          gh api -X POST \
            /repos/${GITHUB_REPOSITORY}/actions/workflows/ur-monitor.yml/dispatches \
            -f ref="$branch" \
            -f inputs:='{"via":"watchdog"}'
